name: hung
description: A new Flutter project.
publish_to: 'none'
version: 0.3.6

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  animated_background: ^2.0.0
  carousel_slider: ^5.0.0
  dotted_border: ^2.1.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_easyloading: ^3.0.5
  flutter_inset_box_shadow: ^1.0.8
  google_fonts: ^6.2.1
  google_generative_ai: ^0.4.3
  google_nav_bar: ^5.0.6
  hive: ^2.2.3
  image_picker: ^1.1.2
  like_button: ^2.0.5
  sensors_plus: ^6.0.1
  shared_preferences: ^2.2.3
  side_rail: ^0.0.5
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  storyly_flutter: ^2.15.0
  toastification: ^2.0.0
  url_launcher: ^6.3.0
  visibility_detector: ^0.4.0+2
  webview_flutter: ^4.8.0
  http: ^1.2.2
  http_parser: ^4.0.2
  insta_image_viewer: ^1.0.4
  permission_handler: ^11.3.1
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.11
  flutter_staggered_grid_view: ^0.7.0
  json_cache: ^3.0.2
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  json_path: ^0.7.4
  haptic_feedback: ^0.5.1+1
  hyper_effects: ^0.2.3
  avatar_glow: ^3.0.1
  user_profile_avatar: ^0.1.3
  device_scan_animation: ^0.0.6
  pretty_animated_buttons: ^0.0.2
  chat_bubbles: ^1.5.0
  hl_image_picker_android: ^1.2.11
  colorgram: ^2.0.0
  listview_screenshot: ^3.1.1
  image_gallery_saver_plus: ^3.0.5
  path_provider: ^2.1.4
  typeid: ^1.0.1
  path: ^1.9.0
  cupertino_clock: ^0.1.0+1
  high_q_paginated_drop_down: ^2.1.0
  full_screen_image: ^2.0.0
  brotli: ^0.6.0
  gpt_markdown: ^0.1.8
  lottie: ^3.1.2
  smooth_page_indicator: ^1.2.0+3
  flutter_svg: ^2.0.10+1
  primer_progress_bar: ^0.5.0
  auto_size_text_plus: ^3.0.2
  flutter_typing_indicator: ^0.0.4
  simple_icons: ^10.1.3


dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3


flutter:
  uses-material-design: true
  assets:
    - images/
    - images/avatars/
    - .env
    - riv/
  fonts:
    - family: hero-icons-outline
      fonts:
            - asset: fonts/hero-icons-outline.ttf
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-ExtraLight.ttf
        - asset: fonts/Poppins-Regular.ttf
    - family: GabrielaStencil
      fonts:
        - asset: fonts/GabrielaStencil-Bold.ttf
          weight: 600
        - asset: fonts/GabrielaStencil-Light.ttf
          weight: 300
    - family: Lato_Italic
      fonts:
        - asset: fonts/Lato-Italic.ttf
    - family: ShantellSans-Medium
      fonts:
        - asset: fonts/ShantellSans-Medium.ttf
